# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lico < Formula
  desc "CLI tool for managing dotfiles"
  homepage "https://github.com/Hayao0819/lico"
  version "0.1.0"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Hayao0819/lico/releases/download/v0.1.0/lico_Darwin_arm64.tar.gz"
      sha256 "7e00fa08f6972c2a90a4cbdf694e6fb5ea8566f92294f5d7345810bdfe8d2d2b"

      def install
        bin.install "lico
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Hayao0819/lico/releases/download/v0.1.0/lico_Darwin_x86_64.tar.gz"
      sha256 "dde551fed380361a2fac56838c12c1fef4b19e473115c93b048b8b026ed251a8"

      def install
        bin.install "lico
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Hayao0819/lico/releases/download/v0.1.0/lico_Linux_arm64.tar.gz"
      sha256 "26e7bd57d69a9d6a4cb90abc8747a1180cdd697738adf6ffcac7dc84d4a4d4fb"

      def install
        bin.install "lico
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Hayao0819/lico/releases/download/v0.1.0/lico_Linux_x86_64.tar.gz"
      sha256 "08583741b5b8986c746b1345e788185e83231c9ae1faea1a7dcd5a6efd1c25e2"

      def install
        bin.install "lico
      end
    end
  end

  test do
    system "#{bin}/lico help"
  end
end
