# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lico < Formula
  desc "CLI tool for managing dotfiles"
  homepage "https://github.com/Hayao0819/lico"
  version "0.2.0"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Hayao0819/lico/releases/download/v0.2.0/lico_Darwin_arm64.tar.gz"
      sha256 "4783ed6abfd9719d126df6bf2739f2d0751864308317d5c3fd4a5c26ed06e193"

      def install
        bin.install "lico
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Hayao0819/lico/releases/download/v0.2.0/lico_Darwin_x86_64.tar.gz"
      sha256 "bc823f0fd8b6de49a8f24266bfbe1a17b976f3d053310ed6ff7db946dea435ae"

      def install
        bin.install "lico
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Hayao0819/lico/releases/download/v0.2.0/lico_Linux_x86_64.tar.gz"
      sha256 "41a3013d1be5c3e0103532ca53156bf3cc41fe15aa2e7c17c0d8edbd378e7334"

      def install
        bin.install "lico
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Hayao0819/lico/releases/download/v0.2.0/lico_Linux_arm64.tar.gz"
      sha256 "4dee38240eae16754ba21e922024134d6afde33dd2846994c68c7a7ade4309ce"

      def install
        bin.install "lico
      end
    end
  end

  test do
    system "#{bin}/lico help"
  end
end
