# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lico < Formula
  desc "CLI tool for managing dotfiles"
  homepage "https://github.com/Hayao0819/lico"
  version "0.1.0"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Hayao0819/lico/releases/download/v0.1.0/lico_Darwin_x86_64.tar.gz"
      sha256 "ee3a98e70f7b13985d61e7180f2f84ef85722132cb0fba8585a17130dbcfe4ce"

      def install
        bin.install "lico
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Hayao0819/lico/releases/download/v0.1.0/lico_Darwin_arm64.tar.gz"
      sha256 "4f26ad9723966c8586520e7b16c1197ad5228452a9e3f87fdeb7f9434e4c721d"

      def install
        bin.install "lico
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Hayao0819/lico/releases/download/v0.1.0/lico_Linux_arm64.tar.gz"
      sha256 "955f8f0e073bac719c69ad43dbaac9e33b5ea840d741d3d00d01dae3793f9361"

      def install
        bin.install "lico
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Hayao0819/lico/releases/download/v0.1.0/lico_Linux_x86_64.tar.gz"
      sha256 "ea35658d1700e1059842d03de076291054879bed7ec98ae7cf53e668ab4891bd"

      def install
        bin.install "lico
      end
    end
  end

  test do
    system "#{bin}/lico help"
  end
end
